const fs = require('fs');
const path = require('path');
const pool = require('./db');

// ── DATA ──────────────────────────────────────────────────────────────────────

const CATEGORIES = [
  { id: 'antique-notes', label: 'Antique Notes', icon: '📜' },
  { id: 'rare-coins', label: 'Rare Coins', icon: '🪙' },
  { id: 'unique-serial', label: 'Unique Serial', icon: '🔢' },
  { id: 'birthday-notes', label: 'Birthday Notes', icon: '🎂' },
  { id: 'anniversary', label: 'Anniversary', icon: '💍' },
  { id: 'event-notes', label: 'Event & Special', icon: '🎉' },
];

const PRODUCTS = [
  { id:'AN001', name:'King George V – One Rupee Note', category:'antique-notes', denomination:'₹1', year:1917, serialNumber:'D/32 123456', condition:'VF', price:8500, originalPrice:11000, rarity:'Rare', description:'A stunning One Rupee note from the British India era bearing the portrait of King George V. Issued by the Government of India in 1917, this note features intricate guilloche patterns and is a prized possession for any colonial currency collector.', historicalInfo:'Issued during World War I, this note was part of the currency reform to address the shortage of silver coins. It bears the signature of A.C. McWatters, Controller of Currency.', gradingDetails:'Centering: Good | Margins: Even | Paper: Crisp | Folds: Light | Color: Bright', tags:['british-india','colonial','george-v','1-rupee'], gradient:'linear-gradient(135deg, #2d4a1e 0%, #1a3a10 50%, #3a5a20 100%)', accentColor:'#7cb87a', image:'https://rukminim2.flixcart.com/image/480/640/xif0q/printed-currency/8/z/2/1-10-different-old-note-collection-1-naaz-rare-collection-original-imahfdszbzgf2gfe.jpeg', featured:true },
  { id:'AN002', name:'King George VI – Ten Rupees', category:'antique-notes', denomination:'₹10', year:1943, serialNumber:'L2 456789', condition:'FINE', price:14500, originalPrice:18000, rarity:'Very Rare', description:'A magnificent Ten Rupee note from 1943, issued under the Governor of the Reserve Bank of India. Features the iconic peacock design with intricate border patterns and KGVI portrait.', historicalInfo:'Printed during the height of World War II, this series featured enhanced security features. The note circulated across British India and was legal tender in multiple princely states.', gradingDetails:'Centering: Fine | Margins: Slightly Uneven | Paper: Smooth | Folds: 2 Light Folds | Color: Good', tags:['british-india','george-vi','wwii','10-rupee'], gradient:'linear-gradient(135deg, #3a2a10 0%, #5a3a18 50%, #4a2e12 100%)', accentColor:'#d4a853', image:'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?w=600&q=80', featured:true },
  { id:'AN003', name:'Republic India – Two Rupees (1949)', category:'antique-notes', denomination:'₹2', year:1949, serialNumber:'A1 001234', condition:'UNC', price:22000, originalPrice:28000, rarity:'Extremely Rare', description:'The very first Two Rupee note issued after Indian independence in 1949. This note bears the Lion Capital of Ashoka — a historic transition from British to Republic India currency.', historicalInfo:'This note was part of the first currency issued by the Republic of India. It replaced the KGVI notes and marked the beginning of a new monetary era. The Ashoka Pillar replaced the British monarch\'s portrait.', gradingDetails:'Centering: Excellent | Margins: Wide | Paper: Original Crisp | Folds: None | Color: Vivid', tags:['republic-india','independence','ashoka','first-series'], gradient:'linear-gradient(135deg, #1a2a4a 0%, #2a3a6a 50%, #1a2a5a 100%)', accentColor:'#7aabde', image:'https://www.marketcalls.in/wp-content/uploads/2011/11/History-of-Rupee.jpg', featured:true },
  { id:'AN004', name:'Hyderabad State – One Rupee Hali', category:'antique-notes', denomination:'1 Hali', year:1948, serialNumber:'H/1 789012', condition:'VF', price:31000, originalPrice:42000, rarity:'Extremely Rare', description:'An exceptionally rare note from the Princely State of Hyderabad, issued just before accession to India. The Osmania Sicca (Hali) was the official currency of Hyderabad and ceased to exist after 1950.', historicalInfo:'The Nizam of Hyderabad issued this note just months before the military operation Polo in 1948. Only a few thousand are known to exist worldwide, making this an extraordinary collector\'s item.', gradingDetails:'Centering: Good | Margins: Adequate | Paper: Slightly Aged | Folds: 3 | Color: Slightly Faded', tags:['princely-state','hyderabad','nizam','hali','pre-independence'], gradient:'linear-gradient(135deg, #3a1a2a 0%, #5a2a3a 50%, #4a1a28 100%)', accentColor:'#e87aab', image:'https://images.unsplash.com/photo-1580519542036-c47de6196ba5?w=600&q=80', featured:false },
  { id:'AN005', name:'Five Rupee Note – Signed by IG Patel', category:'antique-notes', denomination:'₹5', year:1975, serialNumber:'C8 556677', condition:'MINT', price:4500, originalPrice:5500, rarity:'Uncommon', description:'A pristine Five Rupee note signed by Dr. I.G. Patel, the legendary RBI Governor. Notes signed by prominent governors command significant premiums in the collector market.', historicalInfo:'Dr. I.G. Patel served as RBI Governor from 1977-1982 and is revered for his economic reforms. His signature on currency notes is highly sought after by collectors.', gradingDetails:'Centering: Perfect | Margins: Full | Paper: Crisp & Original | Folds: None | Color: Brilliant', tags:['ig-patel','rbi-governor','5-rupee','signed'], gradient:'linear-gradient(135deg, #1a3a2a 0%, #2a5a3a 50%, #1a4a2a 100%)', accentColor:'#7ade9a', image:'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=600&q=80', featured:false },
  { id:'RC001', name:'East India Company – 1/4 Anna (1835)', category:'rare-coins', denomination:'¼ Anna', year:1835, serialNumber:'EIC-QA-1835-001', condition:'FINE', price:18500, originalPrice:24000, rarity:'Very Rare', description:'A quarter Anna coin from 1835, bearing the portrait of King William IV and the East India Company insignia. This coin predates the Crown rule and is one of the earliest standardised Indian coins.', historicalInfo:'The 1835 coinage was the first standardized coinage for all of British India. Prior to this, different presidencies (Bombay, Bengal, Madras) had their own coins.', gradingDetails:'Strike: Bold | Fields: Lightly Toned | Devices: Clear | Edge: Reeded & Complete', tags:['east-india-company','william-iv','anna','colonial','1835'], gradient:'linear-gradient(135deg, #3a3010 0%, #5a4a18 50%, #4a3a12 100%)', accentColor:'#c4962a', image:'https://www.tezbid.com/cdn/shop/files/L09I01_580x.jpg', featured:true },
  { id:'RC002', name:'Republic India – 1 Rupee (1950) – First Issue', category:'rare-coins', denomination:'₹1', year:1950, serialNumber:'RI-1R-1950-Bombay', condition:'UNC', price:35000, originalPrice:45000, rarity:'Extremely Rare', description:'The very first One Rupee coin issued by the Republic of India in 1950, minted at the Bombay Mint. Features the Lion Capital and the words "Bharat" in Devanagari. Absolute gem for collectors.', historicalInfo:'Minted at Bombay (no mint mark), this coin marks the birth of independent India\'s numismatic tradition. The design by Debi Prasad Roy Chowdhury remains iconic.', gradingDetails:'Strike: Full | Luster: Original Brilliant | Surfaces: Pristine | Edge: Milled Perfect', tags:['republic-india','1950','1-rupee','bombay-mint','first-issue'], gradient:'linear-gradient(135deg, #2a1a3a 0%, #3a2a5a 50%, #2a1a4a 100%)', accentColor:'#ab7ade', image:'https://images.unsplash.com/photo-1609692814859-b5e2e3e5e228?w=600&q=80', featured:true },
  { id:'RC003', name:'Kutch State – Kori Coin (1928)', category:'rare-coins', denomination:'1 Kori', year:1928, serialNumber:'KUT-1K-1928-VS1985', condition:'VF', price:12000, originalPrice:16000, rarity:'Rare', description:'A silver Kori coin from the princely state of Kutch, featuring the traditional Trishul and sun design. Minted in Vikram Samvat 1985, this coin represents the rich numismatic tradition of Gujarat.', historicalInfo:'The Kutch State had its own coinage until 1948. The Kori was the standard currency and was accepted across Gujarat and parts of Sindh.', gradingDetails:'Strike: Sharp | Silver: 95% Pure | Toning: Attractive Antique | Devices: Bold', tags:['princely-state','kutch','kori','silver','gujarat'], gradient:'linear-gradient(135deg, #2a3a3a 0%, #3a5a5a 50%, #2a4a4a 100%)', accentColor:'#7adede', image:'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=600&q=80', featured:false },
  { id:'US001', name:'Solid Serial – ₹100 Note (1111111)', category:'unique-serial', denomination:'₹100', year:2015, serialNumber:'11A 1111111', condition:'MINT', price:55000, originalPrice:70000, rarity:'Ultra Rare', description:'An extraordinary "Solid 1" serial number note — all seven digits are 1. Serial number 1111111 is among the most coveted of all fancy serial numbers. Only one such note per print run exists.', historicalInfo:'Solid serial numbers (all same digits) are the pinnacle of fancy serial number collecting. This Gandhi Series ₹100 note with serial 1111111 is a once-in-a-lifetime find.', gradingDetails:'Centering: Perfect | Paper: Superb Gem | Folds: None | Press: Full Original | Color: Brilliant', tags:['solid-serial','fancy','1111111','100-rupee','ultra-rare'], gradient:'linear-gradient(135deg, #3a1a1a 0%, #5a2a2a 50%, #4a1a1a 100%)', accentColor:'#de7a7a', image:'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=600&q=80', featured:true },
  { id:'US002', name:'Radar Serial – ₹50 Note (1234321)', category:'unique-serial', denomination:'₹50', year:2018, serialNumber:'5AB 1234321', condition:'MINT', price:18000, originalPrice:22000, rarity:'Very Rare', description:'A "Radar" serial number note — reads the same forwards and backwards (1234321). These palindromic serial numbers are highly prized in the world of notaphily.', historicalInfo:'Radar notes get their name because like a radar signal, the number reads identically in both directions. The serial 1234321 is particularly beautiful as it also features ascending digits.', gradingDetails:'Centering: Excellent | Paper: Crisp | Folds: None | Color: Perfect', tags:['radar','palindrome','fancy-serial','50-rupee'], gradient:'linear-gradient(135deg, #1a3a1a 0%, #2a5a2a 50%, #1a4a1a 100%)', accentColor:'#7ade7a', image:'https://images.unsplash.com/photo-1589994160839-163cd867cfe8?w=600&q=80', featured:false },
  { id:'US003', name:'Ladder Serial – ₹10 Note (1234567)', category:'unique-serial', denomination:'₹10', year:2020, serialNumber:'1CF 1234567', condition:'MINT', price:12500, originalPrice:15000, rarity:'Rare', description:'A perfect "Ladder" serial number — digits ascend sequentially from 1 to 7. The ascending ladder (1234567) is one of the most classic and sought-after fancy serial numbers.', historicalInfo:'Ladder serials are classified as "True Ladders" when all seven digits are consecutive. This note features the Mahatma Gandhi portrait and Konark Wheel reverse.', gradingDetails:'Centering: Perfect | Paper: Gem Uncirculated | Folds: None | Color: Vivid', tags:['ladder','fancy-serial','ascending','10-rupee'], gradient:'linear-gradient(135deg, #1a2a3a 0%, #2a3a5a 50%, #1a2a4a 100%)', accentColor:'#7aaade', image:'https://images.unsplash.com/photo-1604594849809-dfedbc827105?w=600&q=80', featured:false },
  { id:'BN001', name:'Birthday Note – 15-08-1947 (Independence Day)', category:'birthday-notes', denomination:'₹500', year:2016, serialNumber:'15M 1508194', condition:'MINT', price:28000, originalPrice:35000, rarity:'Extremely Rare', description:'A ₹500 note with serial containing "15081947" — India\'s Independence Day! The ultimate collectible for freedom day birthdays. An incredibly meaningful gift for anyone born on 15th August.', historicalInfo:'Serial numbers containing historic dates are among the most collectible. 15081947 marks the date India became independent, making this note deeply symbolic and historically resonant.', gradingDetails:'Centering: Perfect | Paper: Superb Crisp | Folds: None | Press: Brilliant', tags:['birthday','independence-day','15-august','1947','historical-date'], gradient:'linear-gradient(135deg, #1a1a3a 0%, #2a2a5a 50%, #0a0a2a 100%)', accentColor:'#7a7ade', image:'https://images.unsplash.com/photo-1554672408-730436b60dde?w=600&q=80', featured:true },
  { id:'BN002', name:'Birthday Note – Date 01-01 (New Year)', category:'birthday-notes', denomination:'₹100', year:2019, serialNumber:'7CC 0101XXX', condition:'MINT', price:8500, originalPrice:11000, rarity:'Uncommon', description:'Perfect gift for New Year birthdays (January 1st). Serial contains 0101 — a beautiful New Year date note. Available with various year combinations to match your birthyear.', historicalInfo:'Date-matching currency notes have become a significant gifting tradition in India. Notes matching birthdates are considered auspicious and make unique keepsakes.', gradingDetails:'Centering: Excellent | Paper: Crisp & Clean | Folds: None', tags:['birthday','new-year','january-1','date-note'], gradient:'linear-gradient(135deg, #3a2a1a 0%, #5a3a18 50%, #4a2a12 100%)', accentColor:'#dea87a', image:'https://images.unsplash.com/photo-1633158829585-23ba8f7c8caf?w=600&q=80', featured:false },
  { id:'BN003', name:'Custom Birthday Note – Your Date', category:'birthday-notes', denomination:'₹50', year:2021, serialNumber:'Custom', condition:'MINT', price:5500, originalPrice:7000, rarity:'On Request', description:'We source notes with serial numbers matching your specific birthdate. Provide us your date of birth and we will find the closest matching note from our extensive inventory.', historicalInfo:'Birthday notes make the most personal and meaningful gifts. Our network of collectors across India helps us source notes matching specific dates for our clients.', gradingDetails:'All custom notes are Grade 65 or better | Mint condition guaranteed', tags:['birthday','custom','personalized','gift'], gradient:'linear-gradient(135deg, #2a1a3a 0%, #3a2a5a 50%, #2a1a4a 100%)', accentColor:'#c47ade', image:'https://images.unsplash.com/photo-1561414927-6d86591d0c4f?w=600&q=80', featured:false, isCustom:true },
  { id:'AV001', name:'Golden Anniversary – ₹50 (1974 Dated Serial)', category:'anniversary', denomination:'₹50', year:2024, serialNumber:'5GR 1974XXX', condition:'MINT', price:9500, originalPrice:13000, rarity:'Uncommon', description:'Celebrating 50 years of togetherness? This ₹50 note carries the serial matching 1974 — perfect for couples married in 1974 celebrating their Golden Anniversary in 2024.', historicalInfo:'Anniversary notes have become a cherished Indian gifting tradition. Currency notes matching wedding years represent the timeless value of money and relationships.', gradingDetails:'Centering: Perfect | Paper: Gem | Folds: None | Color: Vivid Gold', tags:['anniversary','golden','50-years','1974','gift'], gradient:'linear-gradient(135deg, #3a2e1a 0%, #5a461a 50%, #4a3818 100%)', accentColor:'#f0c040', image:'https://images.unsplash.com/photo-1582281298055-e25b84a1a81e?w=600&q=80', featured:false },
  { id:'AV002', name:'Silver Anniversary – ₹25 Note (1977)', category:'anniversary', denomination:'₹25', year:1977, serialNumber:'W/15 250000', condition:'UNC', price:16000, originalPrice:20000, rarity:'Rare', description:'The ₹25 denomination was briefly issued and is extremely rare. This note from 1977 is perfect for 25th (Silver) anniversary celebrations. Both rare as a denomination and meaningful as a gift.', historicalInfo:'The ₹25 note was issued only briefly and discontinued. It has become a collector\'s treasure — simultaneously rare and symbolically perfect for 25th anniversary gifts.', gradingDetails:'Centering: Excellent | Paper: Bright | Folds: 1 Light | Color: Clear', tags:['anniversary','silver','25-rupee','rare-denomination','1977'], gradient:'linear-gradient(135deg, #2a2a3a 0%, #3a3a5a 50%, #2a2a4a 100%)', accentColor:'#c0c0de', image:'https://images.unsplash.com/photo-1618761714954-0b8cd0026356?w=600&q=80', featured:true },
  { id:'EV001', name:'Millennium Note – ₹1000 (Year 2000)', category:'event-notes', denomination:'₹1000', year:2000, serialNumber:'1GK 2000001', condition:'MINT', price:65000, originalPrice:85000, rarity:'Ultra Rare', description:'The reintroduced ₹1000 note of the year 2000 with serial starting with 2000 — the millennium note! Now demonetized, these are legal collectibles and extremely valuable.', historicalInfo:'The ₹1000 note was reintroduced in 2000 after a gap of many years. Notes with millennium serials (containing "2000") are among the most sought-after of the post-independence era.', gradingDetails:'Centering: Perfect | Paper: Superb Gem | Folds: None | Signature: Bimal Jalan', tags:['millennium','2000','1000-rupee','demonetized','ultra-rare'], gradient:'linear-gradient(135deg, #1a3a1a 0%, #2a5a2a 50%, #0a2a0a 100%)', accentColor:'#4ade80', image:'https://images.unsplash.com/photo-1592495989226-03f88f8a851e?w=600&q=80', featured:true },
  { id:'EV002', name:'Republic Day Note – ₹26 Set (1950)', category:'event-notes', denomination:'Set', year:1950, serialNumber:'SET-26JAN-1950', condition:'VF', price:145000, originalPrice:200000, rarity:'Museum Grade', description:'An extraordinary set of notes with serial numbers containing "2601" and "1950" commemorating Republic Day (26th January 1950). A museum-grade collectible of immense historical significance.', historicalInfo:'India became a republic on January 26, 1950. Notes from this exact year bearing relevant serials are considered national treasures. This set includes verified authenticated pieces.', gradingDetails:'All pieces: Fine to Very Fine | Authentication: Certified by BNAPS', tags:['republic-day','26-january','1950','set','historical'], gradient:'linear-gradient(135deg, #3a1a2a 0%, #5a2a3a 50%, #2a0a1a 100%)', accentColor:'#de7aab', image:'https://images.unsplash.com/photo-1605792657660-596af9009e82?w=600&q=80', featured:true, isSet:true },
  { id:'EV003', name:'Gandhi Centenary – Special ₹1 Note (1969)', category:'event-notes', denomination:'₹1', year:1969, serialNumber:'GA 1869001', condition:'UNC', price:42000, originalPrice:55000, rarity:'Extremely Rare', description:'A special One Rupee note from 1969 — the centenary year of Mahatma Gandhi\'s birth. Serial containing 1869 (Gandhi\'s birth year) makes this doubly significant.', historicalInfo:'Gandhi\'s 100th birth anniversary in 1969 was celebrated with special currency issues. This note with serial referencing 1869 is among the most meaningful pieces for collectors.', gradingDetails:'Centering: Superb | Paper: Original Bright | Folds: None | Signature: L.K. Jha', tags:['gandhi','centenary','1969','1-rupee','commemorative'], gradient:'linear-gradient(135deg, #3a2a1a 0%, #5a3a18 50%, #3a2212 100%)', accentColor:'#e8a855', image:'https://rukminim2.flixcart.com/image/480/640/xif0q/printed-currency/8/z/2/1-10-different-old-note-collection-1-naaz-rare-collection-original-imahfdszbzgf2gfe.jpeg', featured:false },
];

const GIFT_PACKAGES = [
  { id:'GP001', name:'Birthday Legacy Box', occasion:'Birthday', description:'A curated set of notes and coins matching the recipient\'s birthdate. Comes in a premium walnut box with a certificate of authenticity.', includes:['Date-matching currency note','Year-matching coin','Certificate of Authenticity','Premium walnut presentation box','Handwritten story card'], price:4999, icon:'🎂', color:'#d4a853', popular:true },
  { id:'GP002', name:'Anniversary Treasure Set', occasion:'Anniversary', description:'Celebrate years of love with currency from your wedding year. Each piece tells the story of your special day.', includes:['Wedding year currency note','Vintage coin from marriage year','Gold-foil stamped certificate','Velvet presentation case','Personal history card'], price:6999, icon:'💍', color:'#e87aab', popular:true },
  { id:'GP003', name:'Freedom Collection', occasion:'Republic/Independence Day', description:'Historical notes and coins from 1947-1950 — the founding years of independent India. Perfect national pride gift.', includes:['1947-1950 era note','Independence era coin','Historical pamphlet','Premium display frame'], price:12999, icon:'🇮🇳', color:'#7ade80', popular:false },
  { id:'GP004', name:'Lucky Number Charm', occasion:'Any Occasion', description:'A note with your lucky number sequence. Combine numerology with rare currency for a truly unique gift.', includes:['Lucky serial number note','Numerology card','Velvet pouch'], price:2999, icon:'🍀', color:'#7aaade', popular:false },
  { id:'GP005', name:'Wedding Heirloom Set', occasion:'Wedding', description:'A generational treasure — currency notes from both families\' birth years, presented together as a symbol of union.', includes:['Two date-matching notes','Two year-matching coins','Dual certificate','Carved wooden keepsake box','Family history booklet'], price:9999, icon:'👑', color:'#f0c060', popular:true },
  { id:'GP006', name:'Corporate Milestone Gift', occasion:'Corporate', description:'Mark company anniversaries, retirement, or promotions with rare currency from the founding year. Prestigious and memorable.', includes:['Company founding year note','Commemorative coin','Engraved plaque','Custom certificate','Executive display box'], price:14999, icon:'🏆', color:'#c4962a', popular:false },
];

const BLOG_POSTS = [
  { id:'BP001', title:'The Complete Guide to Grading Indian Currency Notes', excerpt:'Learn how professional numismatists assess the condition of paper currency. From Mint to Good — understanding grading is key to buying smart.', category:'Collector Tips', readTime:'8 min read', date:'2024-12-15', icon:'📊', featured:true, tags:['grading','beginner','tips'] },
  { id:'BP002', title:'History of Indian Paper Currency: From British Era to Digital India', excerpt:'A comprehensive journey through 200 years of Indian currency history — from the East India Company rupees to post-demonetization collectibles.', category:'History', readTime:'15 min read', date:'2024-11-28', icon:'📜', featured:true, tags:['history','british-india','timeline'] },
  { id:'BP003', title:'How to Identify Genuine Antique Notes: 7 Expert Tips', excerpt:'Protecting yourself from counterfeits is crucial. Our expert guide covers watermarks, paper feel, serial number patterns, and authentication techniques.', category:'Authentication', readTime:'10 min read', date:'2024-11-10', icon:'🔍', featured:false, tags:['authentication','security','expert-tips'] },
  { id:'BP004', title:'Fancy Serial Numbers: What Makes a Note Valuable?', excerpt:'Radars, ladders, solids, repeaters — the world of fancy serial numbers is fascinating. Discover which patterns command the highest premiums.', category:'Collector Tips', readTime:'6 min read', date:'2024-10-22', icon:'🔢', featured:false, tags:['serial-numbers','fancy','valuation'] },
  { id:'BP005', title:'Princely State Currencies: Hidden Treasures of India', excerpt:'Before independence, 565 princely states had their own currencies. We explore the rarest and most beautiful notes from Hyderabad, Travancore, Mysore and more.', category:'History', readTime:'12 min read', date:'2024-10-05', icon:'👑', featured:true, tags:['princely-states','rare','history'] },
  { id:'BP006', title:'Birthday Notes as Gifts: The Trend Taking India by Storm', excerpt:'Why are millions of Indians gifting currency notes matching birthdates? We explore the emotional, cultural, and collector value of birthday notes.', category:'Gifting', readTime:'5 min read', date:'2024-09-18', icon:'🎁', featured:false, tags:['birthday','gifting','trends'] },
];

const PLATFORM_STATS = [
  { value:'5,000+', label:'Rare Items', icon:'🏛️' },
  { value:'25+', label:'Years of Trust', icon:'⭐' },
  { value:'10,000+', label:'Happy Collectors', icon:'👥' },
  { value:'100%', label:'Authenticity', icon:'🛡️' },
];

// ── SEED ───────────────────────────────────────────────────────────────────────

async function seed() {
  const client = await pool.connect();
  try {
    // Run schema
    const schema = fs.readFileSync(path.join(__dirname, 'schema.sql'), 'utf8');
    await client.query(schema);
    console.log('Schema created.');

    // Categories
    for (const c of CATEGORIES) {
      await client.query('INSERT INTO categories (id, label, icon) VALUES ($1, $2, $3)', [c.id, c.label, c.icon]);
    }
    console.log(`Inserted ${CATEGORIES.length} categories.`);

    // Products
    for (const p of PRODUCTS) {
      await client.query(
        `INSERT INTO products (id, name, category, denomination, year, serial_number, condition, price, original_price, rarity, description, historical_info, grading_details, tags, gradient, accent_color, image, featured, is_custom, is_set)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20)`,
        [p.id, p.name, p.category, p.denomination, p.year, p.serialNumber, p.condition, p.price, p.originalPrice, p.rarity, p.description, p.historicalInfo, p.gradingDetails, p.tags, p.gradient, p.accentColor, p.image, p.featured, p.isCustom || false, p.isSet || false]
      );
    }
    console.log(`Inserted ${PRODUCTS.length} products.`);

    // Gift packages
    for (const g of GIFT_PACKAGES) {
      await client.query(
        'INSERT INTO gift_packages (id, name, occasion, description, includes, price, icon, color, popular) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)',
        [g.id, g.name, g.occasion, g.description, g.includes, g.price, g.icon, g.color, g.popular]
      );
    }
    console.log(`Inserted ${GIFT_PACKAGES.length} gift packages.`);

    // Blog posts
    for (const b of BLOG_POSTS) {
      await client.query(
        'INSERT INTO blog_posts (id, title, excerpt, category, read_time, date, icon, featured, tags) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)',
        [b.id, b.title, b.excerpt, b.category, b.readTime, b.date, b.icon, b.featured, b.tags]
      );
    }
    console.log(`Inserted ${BLOG_POSTS.length} blog posts.`);

    // Platform stats
    for (const s of PLATFORM_STATS) {
      await client.query('INSERT INTO platform_stats (value, label, icon) VALUES ($1,$2,$3)', [s.value, s.label, s.icon]);
    }
    console.log(`Inserted ${PLATFORM_STATS.length} platform stats.`);

    console.log('\nSeed complete!');
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  } finally {
    client.release();
    await pool.end();
  }
}

seed();
