// ── STATIC DATA — ML & Sons Authentic Product Catalog ──────────────

export const CATEGORIES = [
  { id: 'antique-coins', label: 'Antique Coins', icon: '🪙' },
  { id: 'vintage-notes', label: 'Vintage Notes', icon: '📜' },
  { id: 'fancy-serial', label: 'Fancy Serial Notes', icon: '🔢' },
  { id: 'star-notes', label: 'Star Notes', icon: '⭐' },
  { id: 'bundles', label: 'Bundles & Sets', icon: '📦' },
  { id: 'gifting', label: 'Gifting Specials', icon: '🎁' },
];

export const PRODUCTS = [
  // ── ANTIQUE COINS ──
  {
    id: 'AC001',
    name: 'Victoria Empress One Rupee 1889 – Silver Coin',
    category: 'antique-coins',
    denomination: '₹1',
    year: 1889,
    condition: 'VF (Very Fine)',
    price: 8500,
    originalPrice: 12000,
    rarity: 'Rare',
    description: 'A genuine British India silver One Rupee coin from 1889, featuring Queen Victoria\'s portrait on the obverse with "VICTORIA EMPRESS" inscription. The reverse displays ornate floral patterns with "ONE RUPEE INDIA 1889" text. Well-preserved with clear details.',
    historicalInfo: 'Minted during the height of the British Raj, Victoria Empress coins are among the most sought-after colonial-era silver coins. The 1889 issue has a limited surviving population in collectible grade.',
    tags: ['british-india', 'victoria', 'silver', '1889', 'one-rupee'],
    gradient: 'linear-gradient(135deg, #2d3a1e 0%, #1a2a10 50%, #3a4a20 100%)',
    accentColor: '#c0c0c0',
    image: '/products/victoria-empress-1889-front.jpeg',
    images: ['/products/victoria-empress-1889-front.jpeg', '/products/victoria-empress-1889-back.jpeg'],
    featured: true,
  },
  {
    id: 'AC002',
    name: 'George VI King Emperor One Rupee – Silver Coin',
    category: 'antique-coins',
    denomination: '₹1',
    year: 1940,
    condition: 'Fine',
    price: 4500,
    originalPrice: 6500,
    rarity: 'Uncommon',
    description: 'A silver One Rupee coin from the George VI era (circa 1940s), bearing the King\'s portrait with "GEORGE VI KING EMPEROR" inscription. Reverse shows the Tiger Capitol of Ashoka. Good collector-grade piece with natural patina.',
    historicalInfo: 'George VI coins were the last British coins minted for India before independence in 1947. These coins witnessed the transition from colonial to independent India.',
    tags: ['british-india', 'george-vi', 'silver', '1940s', 'one-rupee'],
    gradient: 'linear-gradient(135deg, #2a2a3a 0%, #3a3a5a 50%, #2a2a4a 100%)',
    accentColor: '#9a9aaa',
    image: '/products/george-vi-rupee-front.jpeg',
    images: ['/products/george-vi-rupee-front.jpeg', '/products/george-vi-rupee-back.jpeg'],
    featured: true,
  },
  {
    id: 'AC003',
    name: 'George V King Emperor One Rupee 1918 – Silver Coin',
    category: 'antique-coins',
    denomination: '₹1',
    year: 1918,
    condition: 'Fine',
    price: 5500,
    originalPrice: 7500,
    rarity: 'Rare',
    description: 'A British India silver One Rupee from 1918, issued during World War I. Features the crowned bust of King George V with "GEORGE V KING EMPEROR" legend. Reverse with ornate floral wreath surrounding "ONE RUPEE INDIA" text.',
    historicalInfo: 'Minted during WWI, these coins were part of massive silver coinage to fund the war effort. The 1918 mintage from British India is particularly collectible among numismatists.',
    tags: ['british-india', 'george-v', 'silver', '1918', 'wwi', 'one-rupee'],
    gradient: 'linear-gradient(135deg, #3a2a10 0%, #5a3a18 50%, #4a2e12 100%)',
    accentColor: '#d4a853',
    image: '/products/george-v-rupee-front.jpeg',
    images: ['/products/george-v-rupee-front.jpeg', '/products/george-v-rupee-back.jpeg'],
    featured: false,
  },

  // ── VINTAGE NOTES ──
  {
    id: 'VN001',
    name: '₹100 Vintage RBI Note – L.K. Jha Signature',
    category: 'vintage-notes',
    denomination: '₹100',
    year: 1967,
    serialNumber: 'AA/85 597678',
    condition: 'VF (Very Fine)',
    price: 3500,
    originalPrice: 5000,
    rarity: 'Uncommon',
    description: 'A vintage ₹100 note from the Reserve Bank of India featuring the old "BIG NOTE" design with Ashoka Pillar. Serial AA/85 597678 with signature of L.K. Jha, RBI Governor (1967-70). Classic collector piece.',
    historicalInfo: 'The old large-format ₹100 notes were phased out in favor of smaller notes. L.K. Jha served as RBI Governor and later as Ambassador to the USA.',
    tags: ['vintage', '100-rupee', 'rbi', 'lk-jha', 'big-note'],
    gradient: 'linear-gradient(135deg, #1a2a3a 0%, #2a3a5a 50%, #1a2a4a 100%)',
    accentColor: '#7aaade',
    image: '/products/100rs-vintage-single.jpeg',
    images: ['/products/100rs-vintage-single.jpeg', '/products/100rs-vintage-bundle-back.jpeg'],
    featured: true,
  },
  {
    id: 'VN002',
    name: '₹5 Old RBI Green Note – Vintage',
    category: 'vintage-notes',
    denomination: '₹5',
    year: 1975,
    serialNumber: '28U 813988',
    condition: 'Good',
    price: 1200,
    originalPrice: 1800,
    rarity: 'Common Vintage',
    description: 'A classic old ₹5 green note from RBI with serial 28U 813988, preserved in protective plastic sleeve. Features the traditional design with Ashoka Pillar and "FIVE RUPEES" text. A great entry-level vintage note for new collectors.',
    historicalInfo: 'The old ₹5 notes were workhorses of Indian commerce for decades. This green series was widely circulated and represents everyday Indian economic history.',
    tags: ['vintage', '5-rupee', 'green', 'rbi', 'plastic-sleeve'],
    gradient: 'linear-gradient(135deg, #1a3a2a 0%, #2a5a3a 50%, #1a4a2a 100%)',
    accentColor: '#7ade9a',
    image: '/products/5rs-rbi-old-green.jpeg',
    featured: false,
  },
  {
    id: 'VN003',
    name: '₹5 Vintage RBI Note – B.N. Adarkar Era',
    category: 'vintage-notes',
    denomination: '₹5',
    year: 1960,
    serialNumber: 'B7 194102',
    condition: 'VF (Very Fine)',
    price: 2500,
    originalPrice: 3500,
    rarity: 'Uncommon',
    description: 'An older series ₹5 note from the Reserve Bank of India, serial B7 194102, featuring the large Ashoka Pillar design. A well-preserved piece in Very Fine condition from the pre-decimal era.',
    historicalInfo: 'This note design predates the Mahatma Gandhi series and represents the classical era of Indian currency design with its larger format and intricate engravings.',
    tags: ['vintage', '5-rupee', 'rbi', 'pre-gandhi-series', 'classic'],
    gradient: 'linear-gradient(135deg, #2a3a2a 0%, #3a5a3a 50%, #2a4a2a 100%)',
    accentColor: '#8ade8a',
    image: '/products/5rs-vintage-single.jpeg',
    images: ['/products/5rs-vintage-single.jpeg', '/products/5rs-vintage-bundle.jpeg', '/products/5rs-vintage-spread.jpeg'],
    featured: false,
  },
  {
    id: 'VN004',
    name: 'Government of India One Rupee Note – Bundle',
    category: 'vintage-notes',
    denomination: '₹1',
    year: 1980,
    serialNumber: '98V 335001+',
    condition: 'UNC Bundle',
    price: 4500,
    originalPrice: 6000,
    rarity: 'Uncommon',
    description: 'A bundle of Government of India One Rupee notes in consecutive serial order (98V 335001 onwards). These "coin notes" were issued by the Ministry of Finance and feature the Ashoka Lion Capitol. Uncirculated condition.',
    historicalInfo: 'Unlike other Indian notes issued by the RBI, the ₹1 note is issued by the Government of India and signed by the Finance Secretary. These small notes are popular collectibles.',
    tags: ['govt-india', '1-rupee', 'bundle', 'consecutive', 'unc'],
    gradient: 'linear-gradient(135deg, #3a2a3a 0%, #5a3a5a 50%, #4a2a4a 100%)',
    accentColor: '#c47ade',
    image: '/products/1rs-govt-india-stack.jpeg',
    images: ['/products/1rs-govt-india-stack.jpeg', '/products/1rs-govt-india-front-back.jpeg', '/products/1rs-govt-india-bundle-old.jpeg'],
    featured: false,
  },
  {
    id: 'VN005',
    name: '₹50 Old Series – Mahatma Gandhi (Parliament Back)',
    category: 'vintage-notes',
    denomination: '₹50',
    year: 2016,
    serialNumber: '8AW 878122',
    condition: 'Circulated',
    price: 800,
    originalPrice: 1200,
    rarity: 'Common',
    description: 'An old design ₹50 note with Mahatma Gandhi portrait, serial 8AW 878122. The reverse features the Indian Parliament House. This older series has been replaced by the new blue ₹50 notes, making these increasingly collectible.',
    historicalInfo: 'The old ₹50 notes with Parliament design were gradually withdrawn after the new Hampi Stone Chariot design was introduced in 2017.',
    tags: ['50-rupee', 'old-series', 'parliament', 'gandhi'],
    gradient: 'linear-gradient(135deg, #3a3a1a 0%, #5a5a2a 50%, #4a4a1a 100%)',
    accentColor: '#dede7a',
    image: '/products/50rs-old-front.jpeg',
    images: ['/products/50rs-old-front.jpeg', '/products/50rs-old-back.jpeg'],
    featured: false,
  },
  {
    id: 'VN006',
    name: '₹10 Vintage RBI Notes – Consecutive Pair',
    category: 'vintage-notes',
    denomination: '₹10',
    year: 1965,
    serialNumber: 'K/26 065396-065397',
    condition: 'VF (Very Fine)',
    price: 3000,
    originalPrice: 4500,
    rarity: 'Uncommon',
    description: 'A pair of consecutive serial number vintage ₹10 RBI notes (K/26 065396 & 065397). Large format "Big Note" design with Ashoka Pillar. Matching consecutive pairs are harder to find and command a premium.',
    historicalInfo: 'The old large-size ₹10 notes were a mainstay of Indian commerce. Consecutive pairs from this era are scarce as most notes were heavily circulated.',
    tags: ['vintage', '10-rupee', 'consecutive', 'pair', 'big-note'],
    gradient: 'linear-gradient(135deg, #1a2a4a 0%, #2a3a6a 50%, #1a2a5a 100%)',
    accentColor: '#7aabde',
    image: '/products/10rs-vintage-pair.jpeg',
    images: ['/products/10rs-vintage-pair.jpeg', '/products/10rs-vintage-single.jpeg'],
    featured: false,
  },

  // ── FANCY SERIAL NUMBER NOTES ──
  {
    id: 'FS001',
    name: '₹20 Solid Serial 222222 – Mint Condition',
    category: 'fancy-serial',
    denomination: '₹20',
    year: 2024,
    serialNumber: '81B 222222',
    condition: 'UNC (Uncirculated)',
    price: 15000,
    originalPrice: 20000,
    rarity: 'Ultra Rare',
    description: 'A pristine ₹20 note with SOLID serial number 222222 — all six digits identical! Serial 81B 222222 in uncirculated mint condition. Solid serial notes are among the rarest and most valuable fancy serial numbers.',
    historicalInfo: 'Only one solid serial note exists per prefix per lakh — making these exceptionally rare. The number 2 is considered auspicious in many cultures, adding to this note\'s desirability.',
    tags: ['solid-serial', 'fancy', '222222', '20-rupee', 'mint', 'unc'],
    gradient: 'linear-gradient(135deg, #3a3a10 0%, #5a5a18 50%, #4a4a12 100%)',
    accentColor: '#f0d040',
    image: '/products/20rs-solid-222222.jpeg',
    featured: true,
  },
  {
    id: 'FS002',
    name: '₹50 Solid Serial 444444 – UNC',
    category: 'fancy-serial',
    denomination: '₹50',
    year: 2023,
    serialNumber: 'ODW 444444',
    condition: 'UNC (Uncirculated)',
    price: 18000,
    originalPrice: 25000,
    rarity: 'Ultra Rare',
    description: 'A stunning ₹50 new series note with SOLID serial 444444. Serial ODW 444444, uncirculated. The new blue ₹50 with Hampi Chariot on reverse. A premium collector piece with solid serial rarity.',
    historicalInfo: 'Solid serial ₹50 notes in the new blue series are highly valued. The combination of a beautiful modern design with an ultra-rare serial makes this a trophy piece.',
    tags: ['solid-serial', 'fancy', '444444', '50-rupee', 'new-series'],
    gradient: 'linear-gradient(135deg, #1a2a4a 0%, #2a4a6a 50%, #1a3a5a 100%)',
    accentColor: '#7ac0de',
    image: '/products/50rs-solid-444444.jpeg',
    featured: true,
  },
  {
    id: 'FS003',
    name: '₹50 Solid Serial 888888 – Lucky Number',
    category: 'fancy-serial',
    denomination: '₹50',
    year: 2023,
    serialNumber: '7FL 888888',
    condition: 'UNC (Uncirculated)',
    price: 22000,
    originalPrice: 30000,
    rarity: 'Ultra Rare',
    description: 'The luckiest solid serial — ₹50 note with serial 7FL 888888! Number 8 symbolizes prosperity and abundance in many Asian cultures. This solid 888888 is one of the most desirable serial numbers in Indian currency collecting.',
    historicalInfo: 'In Chinese and Indian numerology, 8 is the number of wealth and prosperity. Solid 888888 notes can command the highest premiums among all solid serials.',
    tags: ['solid-serial', 'fancy', '888888', '50-rupee', 'lucky', 'prosperity'],
    gradient: 'linear-gradient(135deg, #3a1a1a 0%, #5a2a2a 50%, #4a1a1a 100%)',
    accentColor: '#de7a7a',
    image: '/products/50rs-solid-888888.jpeg',
    featured: true,
  },
  {
    id: 'FS004',
    name: '₹50 Solid Serial 555555 – UNC',
    category: 'fancy-serial',
    denomination: '₹50',
    year: 2023,
    serialNumber: '8FE 555555',
    condition: 'UNC (Uncirculated)',
    price: 18000,
    originalPrice: 24000,
    rarity: 'Ultra Rare',
    description: 'A gorgeous ₹50 note with solid serial 555555 in mint uncirculated condition. Serial 8FE 555555 — perfect for collectors who value symmetry and completeness in their solid serial collection.',
    tags: ['solid-serial', 'fancy', '555555', '50-rupee'],
    gradient: 'linear-gradient(135deg, #1a3a3a 0%, #2a5a5a 50%, #1a4a4a 100%)',
    accentColor: '#7adede',
    image: '/products/50rs-solid-555555.jpeg',
    featured: false,
  },
  {
    id: 'FS005',
    name: '₹50 Solid Serial 333333 – UNC',
    category: 'fancy-serial',
    denomination: '₹50',
    year: 2023,
    serialNumber: '6SE 333333',
    condition: 'UNC (Uncirculated)',
    price: 16000,
    originalPrice: 22000,
    rarity: 'Ultra Rare',
    description: 'A beautiful ₹50 note with SOLID serial 333333 in uncirculated condition. Number 3 represents the holy trinity in many traditions. Complete your solid serial collection with this piece.',
    tags: ['solid-serial', 'fancy', '333333', '50-rupee'],
    gradient: 'linear-gradient(135deg, #2a1a3a 0%, #3a2a5a 50%, #2a1a4a 100%)',
    accentColor: '#ab7ade',
    image: '/products/50rs-solid-333333.jpeg',
    featured: false,
  },
  {
    id: 'FS006',
    name: '₹50 Serial Number 000001 – FIRST NOTE!',
    category: 'fancy-serial',
    denomination: '₹50',
    year: 2023,
    serialNumber: '6HQ 000001',
    condition: 'UNC (Uncirculated)',
    price: 35000,
    originalPrice: 50000,
    rarity: 'Museum Grade',
    description: 'The absolute FIRST note of the series — serial number 000001! This ₹50 note (6HQ 000001) is literally note #1 in its print run. First serial notes are the rarest and most prestigious of all fancy serials.',
    historicalInfo: 'Serial number 000001 is the crown jewel of fancy serial collecting. Only ONE exists per prefix, and getting it in uncirculated condition is extremely rare as banks usually retain these.',
    tags: ['first-serial', 'fancy', '000001', '50-rupee', 'museum-grade'],
    gradient: 'linear-gradient(135deg, #3a2e1a 0%, #5a461a 50%, #4a3818 100%)',
    accentColor: '#f0c040',
    image: '/products/50rs-serial-000001.jpeg',
    images: ['/products/50rs-serial-000001.jpeg', '/products/50rs-serial-000001-bundle.jpeg'],
    featured: true,
  },
  {
    id: 'FS007',
    name: '₹10 Fancy Serial 700000 – Round Number',
    category: 'fancy-serial',
    denomination: '₹10',
    year: 2022,
    serialNumber: '33T 700000',
    condition: 'UNC (Uncirculated)',
    price: 5000,
    originalPrice: 7000,
    rarity: 'Rare',
    description: 'A ₹10 note with the round number serial 700000 (33T 700000). Round numbers ending in multiple zeros are collectible fancy serials. Uncirculated condition with crisp paper.',
    tags: ['fancy-serial', 'round-number', '700000', '10-rupee'],
    gradient: 'linear-gradient(135deg, #3a2a1a 0%, #5a3a18 50%, #3a2212 100%)',
    accentColor: '#e8a855',
    image: '/products/10rs-fancy-700000.jpeg',
    featured: false,
  },
  {
    id: 'FS008',
    name: '₹10 Fancy Serial 1000000 – MILLIONTH NOTE',
    category: 'fancy-serial',
    denomination: '₹10',
    year: 2018,
    serialNumber: 'J2D 1000000',
    condition: 'Circulated',
    price: 8000,
    originalPrice: 12000,
    rarity: 'Very Rare',
    description: 'The millionth note! Serial J2D 1000000 — exactly one million. This ₹10 note represents the milestone serial number and is extremely rare. Note shows gentle circulation but retains clear serial visibility.',
    tags: ['fancy-serial', 'million', '1000000', '10-rupee', 'milestone'],
    gradient: 'linear-gradient(135deg, #1a1a3a 0%, #2a2a5a 50%, #0a0a2a 100%)',
    accentColor: '#7a7ade',
    image: '/products/10rs-fancy-1000000.jpeg',
    featured: false,
  },
  {
    id: 'FS009',
    name: '₹50 Fancy 888786 – Semi-Solid + Holy Number',
    category: 'fancy-serial',
    denomination: '₹50',
    year: 2023,
    serialNumber: '7FLR 888786',
    condition: 'UNC (Uncirculated)',
    price: 5500,
    originalPrice: 8000,
    rarity: 'Rare',
    description: 'A unique ₹50 note combining two collectible patterns — near-solid 888 prefix AND the auspicious number 786. Serial 7FLR 888786. The number 786 holds great significance in Islamic tradition. Mint uncirculated.',
    tags: ['fancy-serial', '786', '888', '50-rupee', 'auspicious'],
    gradient: 'linear-gradient(135deg, #1a3a1a 0%, #2a5a2a 50%, #1a4a1a 100%)',
    accentColor: '#7ade7a',
    image: '/products/50rs-solid-888786.jpeg',
    featured: false,
  },
  {
    id: 'FS010',
    name: '₹20 Fancy Serial 222786 – Holy Number',
    category: 'fancy-serial',
    denomination: '₹20',
    year: 2024,
    serialNumber: '81B 222786',
    condition: 'UNC (Uncirculated)',
    price: 3500,
    originalPrice: 5000,
    rarity: 'Uncommon',
    description: 'A ₹20 note combining the repeating "222" pattern with the holy number "786". Serial 81B 222786. The 786 is considered sacred in Islam, making this a meaningful gift or collectible.',
    tags: ['fancy-serial', '786', '222', '20-rupee', 'auspicious', 'gift'],
    gradient: 'linear-gradient(135deg, #2a3a2a 0%, #3a5a3a 50%, #2a4a2a 100%)',
    accentColor: '#8ade9a',
    image: '/products/20rs-fancy-222786.jpeg',
    featured: false,
  },
  {
    id: 'FS011',
    name: '₹20 Fancy Serial 300000 – Round Number',
    category: 'fancy-serial',
    denomination: '₹20',
    year: 2024,
    serialNumber: '55A B300000',
    condition: 'UNC (Uncirculated)',
    price: 4000,
    originalPrice: 5500,
    rarity: 'Rare',
    description: 'A ₹20 note with the perfect round number serial 300000 (55AB 300000). Round number serials with five trailing zeros are scarce and visually striking. Mint uncirculated condition.',
    tags: ['fancy-serial', 'round-number', '300000', '20-rupee'],
    gradient: 'linear-gradient(135deg, #3a2a3a 0%, #5a3a5a 50%, #4a2a4a 100%)',
    accentColor: '#de7ac4',
    image: '/products/20rs-fancy-300000.jpeg',
    featured: false,
  },

  // ── STAR NOTES ──
  {
    id: 'SN001',
    name: '₹200 Star Notes Bundle – Replacement Series',
    category: 'star-notes',
    denomination: '₹200',
    year: 2018,
    serialNumber: '5DM* 557301+',
    condition: 'UNC Bundle',
    price: 25000,
    originalPrice: 35000,
    rarity: 'Very Rare',
    description: 'A bundle of ₹200 STAR (*) notes in consecutive serial order starting from 5DM*557301. Star notes are replacement notes printed to replace defective ones — they carry a * symbol in the serial number and are much rarer than regular notes.',
    historicalInfo: 'Star notes (marked with *) are printed by BRBNMPL to replace defective notes removed during quality checks. Their limited print runs make them highly collectible.',
    tags: ['star-note', 'replacement', '200-rupee', 'bundle', 'consecutive'],
    gradient: 'linear-gradient(135deg, #3a2e1a 0%, #5a461a 50%, #4a3818 100%)',
    accentColor: '#f0c040',
    image: '/products/200rs-star-full.jpeg',
    images: ['/products/200rs-star-full.jpeg', '/products/200rs-star-bundle-1.jpeg', '/products/200rs-star-bundle-2.jpeg'],
    featured: true,
  },
  {
    id: 'SN002',
    name: '₹10 Star Notes Bundle – Replacement Series',
    category: 'star-notes',
    denomination: '₹10',
    year: 2022,
    serialNumber: '04L* 153556+',
    condition: 'UNC Bundle',
    price: 8000,
    originalPrice: 12000,
    rarity: 'Rare',
    description: 'A bundle of ₹10 STAR (*) replacement notes with consecutive serials starting from 04L*153556. These carry the distinctive * symbol in the serial number panel. Over 40 consecutive notes in uncirculated condition.',
    tags: ['star-note', 'replacement', '10-rupee', 'bundle', 'consecutive'],
    gradient: 'linear-gradient(135deg, #2a2a1a 0%, #3a3a2a 50%, #2a2a1a 100%)',
    accentColor: '#dece7a',
    image: '/products/10rs-star-bundle.jpeg',
    images: ['/products/10rs-star-bundle.jpeg', '/products/10rs-star-bundle-2.jpeg', '/products/10rs-star-single.jpeg'],
    featured: false,
  },
  {
    id: 'SN003',
    name: '₹50 Star Notes Bundle – Replacement Series',
    category: 'star-notes',
    denomination: '₹50',
    year: 2023,
    serialNumber: '0CH* 396001+',
    condition: 'UNC Bundle',
    price: 18000,
    originalPrice: 25000,
    rarity: 'Very Rare',
    description: 'A large bundle of ₹50 STAR (*) replacement notes, starting from serial 0CH*396001. Over 70 consecutive star notes in pristine uncirculated condition. A spectacular star note collection piece.',
    tags: ['star-note', 'replacement', '50-rupee', 'bundle', 'consecutive', 'large-bundle'],
    gradient: 'linear-gradient(135deg, #1a2a3a 0%, #2a4a5a 50%, #1a3a4a 100%)',
    accentColor: '#7abcde',
    image: '/products/50rs-star-bundle-fan.jpeg',
    images: ['/products/50rs-star-bundle-fan.jpeg', '/products/50rs-star-bundle-stack.jpeg', '/products/50rs-star-bundle-stack-2.jpeg'],
    featured: false,
  },

  // ── BUNDLES & SETS ──
  {
    id: 'BN001',
    name: '₹50 Solid Trio Set – 333333, 444444, 555555',
    category: 'bundles',
    denomination: '₹50',
    year: 2023,
    condition: 'UNC Set',
    price: 48000,
    originalPrice: 65000,
    rarity: 'Ultra Rare Set',
    description: 'An extraordinary SET of THREE solid serial ₹50 notes: 333333, 444444, and 555555. All three in uncirculated condition. Owning multiple solid serials together is exceptionally rare — this trio is a true treasure.',
    tags: ['solid-serial', 'set', 'trio', '333333', '444444', '555555', '50-rupee'],
    gradient: 'linear-gradient(135deg, #1a1a2a 0%, #2a2a4a 50%, #1a1a3a 100%)',
    accentColor: '#9a9ade',
    image: '/products/50rs-solid-trio.jpeg',
    featured: true,
  },
  {
    id: 'BN002',
    name: '₹50 Consecutive 555xxx Bundle – 60+ Notes',
    category: 'bundles',
    denomination: '₹50',
    year: 2023,
    serialNumber: '8FE 555532-555594',
    condition: 'UNC Bundle',
    price: 12000,
    originalPrice: 16000,
    rarity: 'Rare',
    description: 'A bundle of 60+ consecutive ₹50 notes starting from 8FE 555532, all sharing the "555" prefix. Consecutive serial bundles with repeating digit patterns are highly collectible. All notes uncirculated.',
    tags: ['bundle', 'consecutive', '555', '50-rupee', 'semi-fancy'],
    gradient: 'linear-gradient(135deg, #2a3a1a 0%, #3a5a2a 50%, #2a4a1a 100%)',
    accentColor: '#aaDE7a',
    image: '/products/50rs-555-bundle-fan.jpeg',
    images: ['/products/50rs-555-bundle-fan.jpeg', '/products/50rs-555-bundle-stack.jpeg'],
    featured: false,
  },
  {
    id: 'BN003',
    name: '₹100 New Series Bundle – Consecutive',
    category: 'bundles',
    denomination: '₹100',
    year: 2023,
    serialNumber: '6CN 707001+',
    condition: 'UNC Bundle',
    price: 15000,
    originalPrice: 20000,
    rarity: 'Uncommon',
    description: 'A fresh bundle of new ₹100 notes with consecutive serial numbers starting from 6CN 707001. These lavender-colored notes with the Rani ki Vav design are in pristine uncirculated condition straight from the bank.',
    tags: ['bundle', 'consecutive', '100-rupee', 'new-series', 'unc'],
    gradient: 'linear-gradient(135deg, #2a1a3a 0%, #4a2a5a 50%, #3a1a4a 100%)',
    accentColor: '#c47ade',
    image: '/products/100rs-new-bundle.jpeg',
    images: ['/products/100rs-new-bundle.jpeg', '/products/100rs-200rs-bundle-fan.jpeg', '/products/100rs-200rs-bundle-fan-2.jpeg'],
    featured: false,
  },

  // ── GIFTING SPECIALS ──
  {
    id: 'GF001',
    name: '₹50 Holy 786 Collection – Auspicious Gift',
    category: 'gifting',
    denomination: '₹50',
    year: 2023,
    serialNumber: '8FE 555786',
    condition: 'UNC (Uncirculated)',
    price: 4500,
    originalPrice: 6500,
    rarity: 'Rare',
    description: 'A ₹50 note ending with the sacred number 786 (8FE 555786). The number 786 is considered very auspicious in Islamic tradition and is believed to bring blessings. Perfect gift for Eid, weddings, or any special occasion.',
    tags: ['786', 'auspicious', 'gift', 'islamic', '50-rupee', 'eid'],
    gradient: 'linear-gradient(135deg, #1a3a2a 0%, #2a5a3a 50%, #1a4a2a 100%)',
    accentColor: '#7ade9a',
    image: '/products/50rs-serial-555786.jpeg',
    featured: false,
  },
  {
    id: 'GF002',
    name: '₹10 Fancy Serial 600000 – Lucky Round Number Gift',
    category: 'gifting',
    denomination: '₹10',
    year: 2022,
    serialNumber: '91A 600000',
    condition: 'UNC (Uncirculated)',
    price: 3500,
    originalPrice: 5000,
    rarity: 'Rare',
    description: 'A ₹10 note with the beautiful round serial 600000 (91A 600000). Round number notes with trailing zeros make excellent gifts symbolizing completeness and perfection. Great for birthdays, housewarmings, or achievements.',
    tags: ['round-number', 'gift', '600000', '10-rupee', 'lucky'],
    gradient: 'linear-gradient(135deg, #3a3a2a 0%, #5a5a3a 50%, #4a4a2a 100%)',
    accentColor: '#dede8a',
    image: '/products/10rs-fancy-600000.jpeg',
    featured: false,
  },
];

export const GIFT_PACKAGES = [
  { id: 'GP001', name: 'Birthday Legacy Box', occasion: 'Birthday', description: 'A curated set of notes matching the recipient\'s birthdate. Comes in a premium box with certificate of authenticity.', includes: ['Date-matching currency note', 'Year-matching coin', 'Certificate of Authenticity', 'Premium presentation box', 'Handwritten story card'], price: 4999, icon: '🎂', color: '#d4a853', popular: true },
  { id: 'GP002', name: 'Anniversary Treasure Set', occasion: 'Anniversary', description: 'Celebrate years of love with currency from your wedding year. Each piece tells the story of your special day.', includes: ['Wedding year currency note', 'Vintage coin from marriage year', 'Gold-foil certificate', 'Velvet presentation case'], price: 6999, icon: '💍', color: '#e87aab', popular: true },
  { id: 'GP003', name: 'Lucky 786 Gift Box', occasion: 'Eid / Blessings', description: 'Sacred 786 serial number notes in a beautiful gift box. Perfect for Eid, weddings, or any auspicious occasion.', includes: ['₹50 note with 786 ending', '₹20 note with 786 ending', 'Blessing card', 'Velvet pouch'], price: 3999, icon: '🌙', color: '#7ade80', popular: true },
  { id: 'GP004', name: 'Collector Starter Kit', occasion: 'Any Occasion', description: 'Perfect for new collectors — includes vintage and modern notes showcasing India\'s currency heritage.', includes: ['1 vintage note (pre-1980)', '1 fancy serial note', '1 star note', 'Collector guide booklet', 'Magnifying glass'], price: 5999, icon: '🔍', color: '#7aaade', popular: false },
  { id: 'GP005', name: 'Wedding Heirloom Set', occasion: 'Wedding', description: 'A generational treasure — currency notes from both families\' birth years, presented together as a symbol of union.', includes: ['Two date-matching notes', 'Two vintage coins', 'Dual certificate', 'Carved wooden keepsake box'], price: 9999, icon: '👑', color: '#f0c060', popular: true },
  { id: 'GP006', name: 'Corporate Milestone Gift', occasion: 'Corporate', description: 'Mark company anniversaries or retirements with rare currency from the founding year. Prestigious and memorable.', includes: ['Founding year note', 'Commemorative coin', 'Engraved plaque', 'Custom certificate', 'Executive display box'], price: 14999, icon: '🏆', color: '#c4962a', popular: false },
];

export const BLOG_POSTS = [
  { id: 'BP001', title: 'The Complete Guide to Grading Indian Currency Notes', excerpt: 'Learn how professional numismatists assess the condition of paper currency. From Mint to Good — understanding grading is key.', category: 'Collector Tips', readTime: '8 min read', date: '2024-12-15', icon: '📊', featured: true, tags: ['grading', 'beginner', 'tips'] },
  { id: 'BP002', title: 'History of Indian Paper Currency: British Era to Modern India', excerpt: 'A journey through 200 years of Indian currency — from East India Company rupees to today\'s colorful new series notes.', category: 'History', readTime: '15 min read', date: '2024-11-28', icon: '📜', featured: true, tags: ['history', 'british-india', 'timeline'] },
  { id: 'BP003', title: 'Star Notes Explained: Why the * Makes Them Special', excerpt: 'Star notes with the * symbol are replacement notes with limited print runs. Learn why they\'re worth collecting.', category: 'Collector Tips', readTime: '6 min read', date: '2024-11-10', icon: '⭐', featured: false, tags: ['star-notes', 'replacement', 'collecting'] },
  { id: 'BP004', title: 'Fancy Serial Numbers: What Makes a Note Valuable?', excerpt: 'Solid serials, ladders, radars, 786 endings — discover which serial number patterns command the highest premiums.', category: 'Collector Tips', readTime: '6 min read', date: '2024-10-22', icon: '🔢', featured: false, tags: ['serial-numbers', 'fancy', 'valuation'] },
  { id: 'BP005', title: 'British India Silver Coins: A Collector\'s Guide', excerpt: 'From Victoria to George VI — everything you need to know about collecting British India one rupee silver coins.', category: 'History', readTime: '12 min read', date: '2024-10-05', icon: '🪙', featured: true, tags: ['coins', 'british-india', 'silver', 'guide'] },
  { id: 'BP006', title: '786 Notes: The Tradition of Gifting Auspicious Serial Numbers', excerpt: 'Why millions of Indians seek currency notes ending in 786. The cultural significance and collector value explained.', category: 'Gifting', readTime: '5 min read', date: '2024-09-18', icon: '🎁', featured: false, tags: ['786', 'gifting', 'auspicious', 'trends'] },
];

export const PLATFORM_STATS = [
  { id: 1, value: '500+', label: 'Rare Items Sold', icon: '🏛️' },
  { id: 2, value: '25+', label: 'Years of Trust', icon: '⭐' },
  { id: 3, value: '1,000+', label: 'Happy Collectors', icon: '👥' },
  { id: 4, value: '100%', label: 'Authenticity', icon: '🛡️' },
];
